name: acceptance-tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  acceptance-tests:
    strategy:
      fail-fast: false
      matrix:
        image_tag: [lts-community, lts-developer, lts-enterprise, latest, developer, enterprise]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: build and vet the provider
        run: make
        env:
          GO111MODULE: on
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: run acceptance tests
        run: |
          while [[ "$(curl -s -o /dev/null -w "%{http_code}" admin:admin@localhost:9000/api/system/info)" != "200" ]]; do echo "waiting for SonarQube to start"; sleep 15; done
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          TF_ACC: 1
          GO111MODULE: on
          SONAR_HOST: http://127.0.0.1:9000
          SONAR_USER: admin
          SONAR_PASS: admin
      - name: Run code coverage
        if: ${{ github.ref == 'refs/heads/master' && matrix.image_tag == 'enterprise'}}
        uses: codecov/codecov-action@v2
    services:
      sonarqube:
        image: sonarqube:${{ matrix.image_tag }}
        ports:
          - 9000:9000
