name: acceptance-tests-dce
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  acceptance-tests:
    strategy:
      fail-fast: false
      matrix:
        env: [.env.dce.lts.yml, .env.dce.yml]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add hosts to /etc/hosts
        run: |
            sudo echo "127.0.0.1 sonarqube.dev.local" | sudo tee -a /etc/hosts      
      - name: Start Sonarqube dce
        run: docker compose -f docker-compose-dce.yml --env-file ${{ matrix.env }} up -d 
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: build and vet the provider
        run: make
        env:
          GO111MODULE: on
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: run acceptance tests
        run: |
          while [[ "$(curl -s -o /dev/null -w "%{http_code}" admin:admin@sonarqube.dev.local/api/system/info)" != "200" ]]; do echo "waiting for SonarQube to start"; sleep 15; done
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          TF_ACC: 1
          GO111MODULE: on
          SONAR_HOST: http://sonarqube.dev.local
          SONAR_USER: admin
          SONAR_PASS: admin
          INSTALLED_VERSION: 9.9
          INSTALLED_EDITION: Datacenter