name: tfplugindocs generate

on:
  pull_request:
    paths:
      - .github/workflows/tfplugindocs-check.yml
      - Makefile
      - docs/**
      - examples/**
      - templates/**
      - sonarqube/**

jobs:
  tfplugindocs_generate:
    name: tfplugindocs generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: '${{ github.head_ref }}'
          repository: '${{ github.pull_request.head.repo.full_name }}'

      - name: Setup Go with version from tools/go.mod
        uses: actions/setup-go@v5
        with:
          go-version-file: tools/go.mod

      - name: Set GOCACHE environment variable
        run: |
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV

      - name: Cache Go build cache
        uses: actions/cache@v4
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ${{ env.GOCACHE }}
          key: ${{ runner.os }}-GOCACHE-${{ hashFiles('go.sum') }}-${{ hashFiles('internal/**') }}

      - name: Cache Go module dependencies
        uses: actions/cache@v4
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

      - name: Install tools and generate documentation
        run: |
          make tools
          make docs

      - name: Commit and push generated documentation
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          message: "[bot] docs: tfplugindocs generate"
          repository: ${{ github.pull_request.head.repo.full_name }}