name: tfplugindocs check

on:
  push:
    branches:
      - master
  
jobs:
  tfplugindocs_check:
    name: tfplugindocs check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: tools/go.mod
          cache-dependency-path: tools/go.sum

      - run: |
          make tools
          make docs
          git add -N docs/
          git diff --exit-code
